% =========================================================================
% Copyright (c) 2008-2014 Audio Communication Group, TU Berlin
% 
% This file is part of WhisPER, a package of interacting MATLAB scripts for 
% designing and controlling experiments in the field of auditory perceptive 
% measurement and evaluation.
% 
% WhisPER is free software: you can redistribute it and/or modify it under 
% the terms of the GNU General Public License as published by the Free 
% Software Foundation, either version 3 of the License, or (at your option) 
% any later version. 
% 
% WhisPER is distributed in the hope that it will be useful, but WITHOUT ANY 
% WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
% FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License along 
% with this program. If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.ak.tu-berlin.de/whisper/ 
% =========================================================================
% 
% This file:
%
% Author :   Martina Vrhovnik and Fabian Brinkmann,
%            Audio Communication Group, TU Berlin
% Email  :   fabian.brinkmann at tu-berlin dot de
% Date   :   Oct. 2013
% Updated:   January 2025 by Nils Rummler | nils.rummler at rwth-aachen.de
%             
% =========================================================================

% This script holds all scale labels/poles:
% Item id (see saqi_items), negative pole, positive pole
% Order of items following the RAQI publication by Weinzierl 2018 in JASA
% the label ends have been rephrased from the publication to better compare
% between the stimulus and the (inner) reference.

SAQI_scale_label = ...   
{...
1 'none' 'very large'; ...
2 'I like it less' 'I like it more'; ...
3 'less suitable' 'better suitable'; ...
4 'more difficult' 'less difficult';...
5 'less balanced' 'better balanced';...
6 'smaller' 'larger';...
7 'softer' 'louder';...
8 'smaller' 'larger';
9 'shorter' 'longer';...
10 'dryer' 'more reverberant';...
11 'weaker' 'stronger';...
12 'weaker' 'stronger';...
13 'less brilliant' 'more brilliant';...
14 'darker' 'brighter';...
15 'attenuated' 'emphasized';...
16 'none' 'very stong';...
17 'none' 'very stong';...
18 'none' 'very stong';...
19 'less boomy' 'more boomy';...
20 'less rough' 'more rough';...
21 'none' 'very strong';...
22 'less clear' 'more clear';...
23 'blurred' 'more transparent';...
24 'more diffuse' 'more precise';...
25 'more dead' 'more lively';...
26 'lower' 'higher';...
27 'smaller' 'larger';...
28 'more remote' 'more intimate';...
29 'closer' 'more distant';...
30 'cooler' 'warmer';...
31 'less metallic' 'more metallic';...
32 'more constricted' 'more open';...
33 'softer' 'crisper';...
34 'lower' 'higher';...
35 'button' 'top';...
36 'button' 'top';...
37 'button' 'top';...
37 'button' 'top';...
39 'button' 'top';...
40 'button' 'top';...
41 'button' 'top';...
42 'button' 'top';...
43 'button' 'top';...
44 'button' 'top';...
45 'button' 'top';...
46 'button' 'top';...
47 'button' 'top';...
48 'less pronounced' 'more pronounced';...
};
