% =========================================================================
% Copyright (c) 2008-2014 Audio Communication Group, TU Berlin
% 
% This file is part of WhisPER, a package of interacting MATLAB scripts for 
% designing and controlling experiments in the field of auditory perceptive 
% measurement and evaluation.
% 
% WhisPER is free software: you can redistribute it and/or modify it under 
% the terms of the GNU General Public License as published by the Free 
% Software Foundation, either version 3 of the License, or (at your option) 
% any later version. 
% 
% WhisPER is distributed in the hope that it will be useful, but WITHOUT ANY 
% WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
% FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License along 
% with this program. If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.ak.tu-berlin.de/whisper/ 
% =========================================================================
% 
% This file:
%
% Author :   Martina Vrhovnik and Fabian Brinkmann,
%            Audio Communication Group, TU Berlin
% Email  :   fabian.brinkmann at tu-berlin dot de
% Date   :   Oct. 2013
% Updated:   January 2025 by Nils Rummler | nils.rummler at rwth-aachen.de
%             
% =========================================================================

% Order of items following TABLE 2 of the RAQI publication by Weinzierl 2018 in JASA
SAQI_definition = ...
    {...
    1 'Existence of a noticeable difference.';...
    2 'Evaluation with regard to the acoustic appearance of the presentation.';...
    3 'Aural qualifiction of a room for the given kind of performance.';...
    4 {'Impression of how well the words of a speaker can be understood.'; ...
       '- Typical for low speech intelligibility: train station announcements'; ...
       '- Typical for high speech intelligibility: newscaster'};...
    5 'Balance of auditory objects in all respects.';...
    6 'Perceived total extent of an auditory object.';...
    7 'Percieved intensity and volume of all sound sources in the scene.'
    8 'Perceived spatial extent of a sound source in horizontal direction.';...
    9 'Duration of the reverberant decay. Well audible at the end of signals.';...
    10 {'Perception of a strong reverberant sound field, caused by a high ratio of reflected to direct sound energy.' ;...
       'Leads to the impression of high diffusivity in case of stationary excitation (in the sense of a low D/R-ratio).';... 
       'Example: The perceived intensity of reverberation differs significantly between rather small and very large spaces, such as living rooms and churches.'};...      
    11 {'Strength of spatial sound components, due to the ratio of reflected to direct sound energy.';...
        'The duration of the reverberation should be explicitly ignored here!'};...
    12 {'Sensation of being spatially surrounded by the reverberation. With more pronounced envelopment of reverberation, it is increasingly difficult to assign a specific position, a limited extension or a preferred direction to the reverberation.';... 
       'Impressions of either low or high reverberation envelopment arise with either diotic or dichotic (i.e., uncorrelated) presentation of reverberant audio material.'};...
    13 {'How shiny is the timbral impression, especially at high frequency. Is the signal clear/bright?';...
        'Not to be interpreted in a bad way like a sharp or aggressive sound.'};...
    14 'Timbral impression which is determined by the ratio of high to low frequency components.';...
    15 {'Timbral change in the limited frequency range of high frequencies.'; ...
       'More from a technical perspective: does the sound feel dampened or exaggerated clear?'};...
    16 {'A series of reflections that arrive in a static pattern very shortly after each other.';...
        'Happens when clapping the hands between two parallel surface like in a tunnel or in a long hallway.'};...
    17 {'Copies of a sound with mostly decreasing loudness after the actually intended the starting point of a sound.';... 
       'Example: Repetition of one''s own voice through reflection on mountain walls.'};...
    18 {'Is there any unexpected artifacts or discontinuities in the decay if the sound.';...
        'Especially prominent after impulsive sound events.'};...
    19 {'Timbral change in a limited frequency range of low mid frequencies.';...
        'Strong low-frequency reverberation, typically triggered by narrow-band resonances.';...
        'Depending on the signal, it can also be perceived as thumping.'};...
    20 {'Timbral impression of fierce or aggressive modulation/vibration, whereas individual oscillations are hardly distinguishable.'; ...
        'Not perceived as loudness fluctuation.';...
        'Often rated as unpleasant.'};...
    21 {'Often perceived as tonal coloration. "Hollow" sound.'; ...
      'Example: Speaking through a tube.'};...
    22 'Distinguishability of temporally successive auditory events';...
    23 'Local Distinctness of auditory events';...
    24 {'Spatial extend and location of a sound source. Is often associated with high/low perceivved extend of a sound source';...
        'Examples:';...
        '- Low localizibility: to diffuse appearance of source.';...
        '- High localizibility: clearly delimted source.'};
    25 'Placeholder';...
    26 'Placeholder';...
    27 'Placeholder';...
    28 'Degree of inclusion in the sound performance';...
    29 'Perceived distance of an auditory object';...
    30 'A warm tone color can be created by emphasizing low or low-mid frequeny components.';...
    31 {'Coloration with pronounced narrow-band resonances, often as a result of low density of natural frequencies.';... 
        'Typical for the sound of metallic objects such as gongs, bells, tin cans.'};...
    32 {'Openness is related to the feeling of a wide and transparent acoustic scene.';...
        'The opposite would be a spatially narrow, limited overall impression.'};...
    33 'With crisp attack, the room response to an excitation with a signal is felt immediately.';...
    34 'Everything is there and well audible, without being too much.';...
    35 'Placeholder';...
    36 'Placeholder';...
    37 'Placeholder';...
    38 'Placeholder';...
    39 'Placeholder';...
    40 'Placeholder';...
    41 'Placeholder';...
    42 'Placeholder';...
    43 'Placeholder';...
    44 'Placeholder';...
    45 'Placeholder';...
    46 'Placeholder';...
    47 'Placeholder';...
    48 'Another, previously unrecognized difference.';...
     };
