% =========================================================================
% Copyright (c) 2008-2014 Audio Communication Group, TU Berlin
% 
% This file is part of WhisPER, a package of interacting MATLAB scripts for 
% designing and controlling experiments in the field of auditory perceptive 
% measurement and evaluation.
% 
% WhisPER is free software: you can redistribute it and/or modify it under 
% the terms of the GNU General Public License as published by the Free 
% Software Foundation, either version 3 of the License, or (at your option) 
% any later version. 
% 
% WhisPER is distributed in the hope that it will be useful, but WITHOUT ANY 
% WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
% FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License along 
% with this program. If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.ak.tu-berlin.de/whisper/ 
% =========================================================================
% 
% This file:
%
% Author :   Martina Vrhovnik and Fabian Brinkmann,
%            Audio Communication Group, TU Berlin
% Email  :   fabian.brinkmann at tu-berlin dot de
% Date   :   Oct. 2013
% Updated:   January 2025 by Nils Rummler | nils.rummler at rwth-aachen.de
%             
% =========================================================================

% This script holds all SAQI items and its properties, which are:
% Item id, item name, is_dichotom, is_unipolar, item category,is_degree_scale
% Order of items following  TABLE 2 of the RAQI  publication by Weinzierl 2018 in JASA
SAQI_Items = ...
    {...                              % d u c °
    1 'difference'                      0 1 0 0;... % Mandatory
    2 'Liking'                          0 0 1 0;... % Factor Quality
    3 'Room acoustic suitability'       0 0 1 0;...
    4 'Ease of listening'               0 0 1 0;...
    5 'Global balance'                  0 0 1 0;...
    6 'Size'                            0 0 2 0;... % Factor Strength
    7 'Loudness'                        0 0 2 0;...
    8 'Width'                           0 0 2 0;...
    9 'Duration of the Reverb'          0 0 3 0;... % Factor Reverberance
    10 'Reverberance'                   0 0 3 0;...
    11 'Strength of reverberation'      0 0 3 0;...
    12 'Envelopment by reverberation'   0 0 3 0;...
    13 'Brilliance'                     0 0 4 0;... % Factor Brilliance
    14 'Tone Color'                     0 0 4 0;...
    15 'Treble range characteristic'    0 0 4 0;...
    16 'Flutter Echo'                   0 1 5 0;... % Factor Irregular decay
    17 'Echo'                           0 1 5 0;...
    18 'Irregularity in sound decay'    0 1 5 0;...
    19 'Boominess'                      0 0 6 0;... % Factor Coloration
    20 'Roughness'                      0 0 6 0;...
    21 'Comb filter coloration'         0 1 6 0;...
    22 'Temporal clarity'               0 0 7 0;... % Factor Clarity
    23 'Spatial transparency'           0 0 7 0;...
    24 'Precision of localization'      0 0 7 0;...
    25 'Liveliness'                     0 0 8 0;... % Factor Liveliness
    26 'Spatial presence'               0 0 8 0;...
    27 'Dynamic range'                  0 0 8 0;...
    28 'Intimacy'                       0 0 9 0;... % Factor Intimacy
    29 'Distance'                       0 0 9 0;...
    30 'Warmth'                         0 0 9 0;...
    31 'Metallic tone color'            0 0 10 0;...% Single Items
    32 'Openess'                        0 0 10 0;...
    33 'Attack'                         0 0 10 0;...
    34 'Richness of Sound'              0 0 10 0;...
    35 'Placeholder 35'                 0 0 11 0;...% Placeholders
    36 'Placeholder 36'                 0 0 11 0;...% for consitency
    37 'Placeholder 37'                 0 0 11 0;...
    38 'Placeholder 38'                 0 0 11 0;...
    39 'Placeholder 39'                 0 0 11 0;...
    40 'Placeholder 40'                 0 0 11 0;...
    41 'Placeholder 41'                 0 0 11 0;...
    42 'Placeholder 42'                 0 0 11 0;...
    43 'Placeholder 43'                 0 0 11 0;...
    44 'Placeholder 44'                 0 0 11 0;...
    45 'Placeholder 45'                 0 0 11 0;...
    46 'Placeholder 46'                 0 0 11 0;...
    47 'Placeholder 47'                 0 0 11 0;...
    48 'other'                          0 0 0 0;... % Mandatory
    };
